### ISSUE TITLE
Week 7 Teacher Review

### ISSUE THREAD

**Issue by KaavyaU** [KaavyaU/spring_portfolio#40]
[Runtime Video](https://github.com/KaavyaU/spring_portfolio/issues/40)

[Unit 7 Individual Work](https://github.com/KaavyaU/spring_portfolio/issues/39)

[Week 7 Checkpoint Planning](https://github.com/KaavyaU/spring_portfolio/issues/38) - Code from each person linked below
- [Jacqueline's Code ](https://github.com/KaavyaU/spring_portfolio/issues/45)- Frontend
- [Dhruv's Code ](https://github.com/KaavyaU/spring_portfolio/issues/44)- Control
- [Kaavya's Code ](https://github.com/KaavyaU/spring_portfolio/issues/42)- Model
- [Chris's Code ](https://github.com/KaavyaU/spring_portfolio/issues/43)- Model

[Deployment](https://github.com/KaavyaU/spring_portfolio/issues/41)

**Comment by rpeddakama** [comment]
Notes on peer grading:

Video: Could have been shortened (not concise)
Scrum board: Good organization (showing tasks of individual issues, assignees, progress, and organized columns)
Operation and Run: works as expected
Needs Improvement: Controller could be more concise (repetitive code)

Grading (Team Total 5/5)
View: 1/1 (frontend is nice and user experience is well thought out)
Control: 1/1 (If improvements were made to make code more java-like, it would be nice)
Model: 3/3 (model works exactly as expected and all information is shown)

Journals:
Kaayva - 3/3
Dhruv - 3/3
Chris - 3/3
Jaquline - 1.5/3 (missing tpt and tech talk notes)

**Comment by KaavyaU** [comment]
- Kaavya- 8/8
- Jacqueline - 6.5/8
