### ISSUE TITLE
Unit 8 Work

### ISSUE THREAD

**Issue by KaavyaU** [KaavyaU/spring_portfolio#55]
Total Scores
- Chris: 9.5/10
- Dhruv: 9.5/10
- Jacqueline: 9/10
- Kaavya: 8.9/10 (-0.1 b/c was absent on presentation day)
- Best Suggestions - [Implementation of Grayscale Badges](https://github.com/KaavyaU/spring_portfolio/issues/56), [Complete Deployment](https://github.com/KaavyaU/spring_portfolio/issues/57)
---------------------------------
[Presentation](url)
- 32 comments given

Leaderboard (In Progress) - Kaavya
Events Pages (In Progress) - Jacqueline
View Improvement (Completed) - Dhruv 
Nav bar organization - Kaavya
Minilabs - Chris
  - GrayScale (In Progress)
  - Algorithm, Link to individual person pages (In Progress)
  - Integrate Greet/Birds (In Progress)
  - Binary Hack-a-thon (Not Started)
About us page improvement (Completed) - Dhruv

Individual Code

Unit 8 Individual Work
[Dhruv](https://docs.google.com/document/d/1IWD2lIW_NAtg5wfo1ai5Eg3NYYReTAmgSl1EIhs18i0/edit?usp=sharing) 
[Chris](https://docs.google.com/document/d/1HOltMHftLkMKBBjEFw3E_RmZhZ1Uh3_UKKic3amMDUE/edit?usp=sharing)
Kaavya - [Notes](https://docs.google.com/document/d/1RIIQLuQYmd7VfgwVUuagS0k8c6wzEtOcaqYy5M8PtLE/edit?pli=1#bookmark=id.7taa7u37wozm), [Progress Check](https://docs.google.com/document/d/1RIIQLuQYmd7VfgwVUuagS0k8c6wzEtOcaqYy5M8PtLE/edit?pli=1#bookmark=id.120mpwgldhs0)
Jacqueline - [Journal](https://docs.google.com/document/d/14Yg_BGEkdsSiM5gtYqWaB8CtQvHbF0U7JsSE_vZx_lA/edit?usp=sharing)
Deployment Progress - Working on rasberry pi, or may use github

Ascii Lab - In progress (All members are working)

**Comment by D1935827V** [comment]
I really liked the idea of your project. Recycling is very important to keeping the planed a clean and healthy place.

**Comment by risaiwazaki** [comment]
I really like how you touch on issues in the real world and the overall idea for your project seems very meaningful.

**Comment by akprathipati** [comment]
I really like the ideas and you UI looks top class. I think your initiave but I thinking logging your leaderboard might not work if people put in "fake data" SO I think you need a failsafe for that. Overall, you have an excellent idea and pretty good implementation.

**Comment by avabrooks** [comment]
I liked how you incorporated the presentation and the overall ideas and overview of the project.

**Comment by zenxha** [comment]
Very nice frontend!

**Comment by crystalwidjaja** [comment]
Very structured view of the future goals of the website. Good job!

**Comment by purplebears321** [comment]
I like how you were able to efficiently integrate the project based learning alongside your project purpose!
