### ISSUE TITLE
Dhruv Individual Video

### ISSUE THREAD

**Issue by KaavyaU** [KaavyaU/spring_portfolio#60]
https://youtu.be/7i_WxQuxx_E

**Comment by jm1021** [comment]
Glad to see your video and focus on 2D arrays and PBL.  It is good to see your code.  Three things to consider...
1.) Intro/Setup, you did great job here.   2.) Code, some discussion here but points about 2D arrays I did not understad.  3.) Demo, I did not remember 2D array demo or usage.

Lack of demo left me a little in confusion on both topics 5.25/6

**Comment by jm1021** [comment]
On scores, I saw some WOW in Chris and Kaavya.  Perhaps a suggestion on what to share that would give that experience.  For instance, I am suggesting demo on segments of code you shared.  I do see WOW in some of your notes and background.   1.5/2
